# Various switches to configure build

#Compile in consistency checks?
CPPFLAGS += -DDO_SANITY_CHECKS

#Firmware dependent build options
#--------------------------------

#Build the source for reduced clock architecture
#uncomment for toolflow / comment for BSP
CPPFLAGS += -DREDUCED_CLK_ARCH

#Build the source for legacy wishbone mapping
#CPPFLAGS += -DWISHBONE_LEGACY_MAP

#Build the source for multilink architecture support
CPPFLAGS += -DMULTILINK_ARCH

# Extra Features
#--------------------------------

CPPFLAGS += -DLINK_MONITOR

CPPFLAGS += -DHMC_RECONFIG_RETRY
CPPFLAGS += -DPREEMPT_CONFIGURE_FABRIC_IF

#omit some diagnostic output to reduce elf size
#CPPFLAGS += -DPRUNE_CODEBASE_DIAGNOSTICS
