# Various switches to configure build

#Compile in consistency checks?
CPPFLAGS += -DDO_SANITY_CHECKS

#Firmware dependent build options
#--------------------------------

#Build the source for reduced clock architecture
#uncomment for toolflow / comment for BSP
CPPFLAGS += -DREDUCED_CLK_ARCH

#Build the source for legacy wishbone mapping
#CPPFLAGS += -DWISHBONE_LEGACY_MAP

# Extra Features
#--------------------------------

#enable either -DLINK_MON_RX_40GBE or -DRECONFIG_UPON_NO_DHCP
#but not both
#CPPFLAGS += -DLINK_MON_RX_40GBE
CPPFLAGS += -DRECONFIG_UPON_NO_DHCP

CPPFLAGS += -DHMC_RECONFIG_RETRY
CPPFLAGS += -DPREEMPT_CONFIGURE_FABRIC_IF
